// Code generated by "stringer -type=Class -trimprefix=Class"; DO NOT EDIT.

package asn1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClassUniversal-0]
	_ = x[ClassApplication-1]
	_ = x[ClassContextSpecific-2]
	_ = x[ClassPrivate-3]
}

const _Class_name = "UniversalApplicationContextSpecificPrivate"

var _Class_index = [...]uint8{0, 9, 20, 35, 42}

func (i Class) String() string {
	if i >= Class(len(_Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
