name: Tests
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    uses: codello/.github/.github/workflows/go-test.yml@v1
    with:
      go-versions: go.mod,1.24.x
      test-on: ubuntu-latest,macos-latest,windows-latest
